name: Test workflow

on:
  push:
    branches:
      - main

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  login:
    name: 'login using az cli'
    runs-on: ubuntu-latest

    steps:
      # Make it conditional??
      # .secrets file which you add to .gitignore
      - name: Install azure-cli
        uses: pietrobolcato/install-azure-cli-action@v1

      - name: Azure Version
        run: az --version